import CssBaseline from '@mui/material/CssBaseline'
import { ThemeProvider } from '@mui/material/styles'
import Head from 'next/head'
import '../styles/reset_styles.scss'
import '../styles/global.scss'
import React from 'react'
import { AppPropsWithLayout, EmptyLayout } from '@components/layout'
import theme from '@themeProvider/ThemeProvider'
import { NotificationProvider } from '@components/Notification'
import { SnackbarProvider } from 'notistack'

// Client-side cache, shared for the whole session of the user in the browser.
// const clientSideEmotionCache = createEmotionCache()

function MyApp({ Component, pageProps }: AppPropsWithLayout) {
  const Layout = Component.Layout ?? EmptyLayout

  return (
    <ThemeProvider theme={theme}>
      <CssBaseline />
      <SnackbarProvider anchorOrigin={{ vertical: 'top', horizontal: 'right' }} autoHideDuration={150000} maxSnack={3}>
        <NotificationProvider />
        <Head>
          <title>{pageProps.title}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </SnackbarProvider>
    </ThemeProvider>
  )
}

export default MyApp
